[project]
name = 'test-POAP-like-Course-Completion-Proof_NFT-badges-per-course'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts."POAP-like-Course-Completion-Proof–NFT-badges-per-course"]
path = 'contracts/POAP-like-Course-Completion-Proof–NFT-badges-per-course.clar'
clarity_version = 3
epoch = 3.1

[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
